# Generated by Django 6.0.2 on 2026-02-19 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for current position', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of achievements, e.g. ["Built X", "Led Y"]')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('honeypot', models.CharField(blank=True, help_text='Anti-spam hidden field', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_slug', models.SlugField(help_text='Public URL slug, e.g., /sait27', unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g., Full-Stack Python Developer', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, help_text='Cloudinary URL for profile photo')),
                ('resume', models.URLField(blank=True, help_text='Cloudinary URL for resume PDF')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_platform_admin', models.BooleanField(default=False, help_text='Super admin flag — platform owner only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField(blank=True, help_text='SVG or icon image URL')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('thumbnail', models.URLField(blank=True, help_text='Cloudinary URL for cover image')),
                ('description', models.TextField(blank=True, help_text='Detailed project description (supports markdown)')),
                ('short_description', models.CharField(blank=True, help_text='One-liner for card view', max_length=300)),
                ('category', models.CharField(choices=[('fullstack', 'Full Stack'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('automation', 'Automation'), ('other', 'Other')], default='other', max_length=50)),
                ('live_url', models.URLField(blank=True, help_text='Deployed site URL')),
                ('repo_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on hero section')),
                ('is_visible', models.BooleanField(default=True, help_text='Toggle visibility without deleting')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('date_built', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='api.skill')),
            ],
            options={
                'ordering': ['order', '-date_built'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
