# Generated by Django 6.0.2 on 2026-02-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=100)),
                ('client_avatar', models.URLField(blank=True, help_text='Cloudinary URL for client photo')),
                ('content', models.TextField(help_text='Testimonial text')),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('excerpt', models.TextField(help_text='Brief description for cards', max_length=500)),
                ('content', models.TextField(help_text='Full article content (supports markdown)')),
                ('thumbnail', models.URLField(blank=True, help_text='Cloudinary URL for cover image')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags, e.g. ["React", "Django"]')),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
