# Generated by Django 6.0.2 on 2026-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_new_sections_and_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_nav_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_activities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_certifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_nav_testimonials',
            field=models.BooleanField(default=True),
        ),
    ]
