# Generated by Django 6.0.2 on 2026-02-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_show_nav_about_profile_show_nav_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_section_order',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered dashboard section ids, e.g. ["portfolio_metrics", "quick_actions", "needs_attention"]',
            ),
        ),
    ]
